build_from_template:
  image: linuxserver/sonarr
  version: 3.0.9.1549-ls154
build_from:
  armhf: linuxserver/sonarr:arm32v7-3.0.9.1549-ls154
  aarch64: linuxserver/sonarr:arm64v8-3.0.9.1549-ls154
  amd64: linuxserver/sonarr:amd64-3.0.9.1549-ls154
squash: false
