name: sonarr
version: "0.1.0"
slug: sonarr
legacy: false
init: false
description: PVR for usenet and bittorrent users
url: https://github.com/attiasr/hassio-addons/tree/master/sonarr#readme
image: c0m4/hassio-sonarr-{arch}
startup: services
arch:
  - aarch64
  - amd64
  - armhf
ports:
  8989/tcp: 8989
ports_description:
  8989/tcp: web interface
map:
  - config:rw
  - share:rw
  - media:rw
  - ssl
webui: http://[HOST]:[PORT:8989]
boot: auto
options:
  PUID: 1001
  PGID: 1001

schema:
  PUID: int
  PGID: int
  TZ: str?

backup_exclude:
  - "**/Backups/*"
  - "**/logs/*"
  - "**/MediaCover/*"
