build_from_template:
  image: linuxserver/jackett
  version: v0.20.1685-ls74
build_from:
  armhf: linuxserver/jackett:arm32v7-v0.20.1685-ls74
  aarch64: linuxserver/jackett:arm64v8-v0.20.1685-ls74
  amd64: linuxserver/jackett:amd64-v0.20.1685-ls74
squash: false
