build_from_template:
  image: linuxserver/transmission
  version: 3.00-r5-ls133

build_from:
  armhf: linuxserver/transmission:arm32v7-3.00-r5-ls133
  aarch64: linuxserver/transmission:arm64v8-3.00-r5-ls133
  amd64: linuxserver/transmission:amd64-3.00-r5-ls133
squash: false
