name: transmission
version: 0.1.0
slug: transmission
legacy: false
init: false
# image: c0m4/hassio-transmission-{arch}
description: A fork of Sonarr to work with movies à la Couchpotato
url: https://github.com/attiasr/hassio-addons/tree/master/transmission#readme
startup: services
arch:
  - aarch64
  - amd64
  - armhf
ports:
  9091/tcp: 9091
  51413/tcp: 51413
  51413/udp: 51413
ports_description:
  9091/tcp: web interface
  51413/tcp: Torrent Port TCP
  51413/udp: Torrent Port UDP
map:
  - config:rw
  - share:rw
  - media:rw
  - ssl
webui: http://[HOST]:[PORT:9091]
boot: auto
options:
  PUID: 1001
  PGID: 1001
schema:
  PUID: int
  PGID: int
  TZ: str?
  USER: str?
  PASSWORD: str?
  WHITELIST: str?
  TRANSMISSION_WEB_HOME: str?
backup_exclude: []
